[project]
name = "agentes-ventas-reservas"
version = "0.1.0"
description = ""
authors = [
    {name = "Aldo Abril",email = "aldoabril@gmail.com"}
]
package-mode = false
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0.0"
dependencies = [
    "python-dotenv>=1.0.0",
    "langchain>=0.2.0",
    "langchain-core>=1.0.0",
    "langchain-community>=0.2.0",
    "langchain-openai>=0.1.0",
    "langchain-text-splitters>=0.2.0",
    "langchain-chroma>=0.1.0",
    "chromadb>=0.5.0",
    "langgraph>=0.1.0",
    "pydantic<3",
    "numpy",
    "openai",
    "tiktoken",
    "pypdf",
    "langchain-google-genai>=0.1.0"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
